# Generated by Django 5.1.8 on 2025-04-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('lamp', 'Lamp'), ('thermostat', 'Thermostat')], max_length=20)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
